version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mqtt-take1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ahwqtn21zlft"
s3_prefix = "mqtt-take1"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
